# iterm2
add_newline = true

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[gcloud]
disabled = true

[aws]
format = '[ $profile](bold yellow)'
disabled = false

[ruby]
disabled = true

[lua]
disabled = true

[docker_context]
disabled = true

[golang]
format = '[ $version ](bold blue)'
