add_newline = true

[git_branch]
symbol = " "

[git_status]
style = "bold purple"

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[gcloud]
disabled = true

[aws]
disabled = false
symbol = ' '
format = 'using [$symbol($profile )(\[$duration\] )]($style)'

[ruby]
disabled = true

[python]
symbol = ' '
format = '[$symbol$version ](blue)'

[lua]
disabled = true

[docker_context]
disabled = true

[golang]
format = '[ $version ](bold blue)'
