"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
$username\
[](bg:color_purple fg:color_bg1)\
$directory\
[](fg:color_purple bg:color_mauve)\
$git_branch\
$git_status\
[](fg:color_mauve bg:color_gray)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_gray)\
$line_break$character"""

palette = 'custom'

[palettes.custom]
color_fg0 = '#fbf1c7'   # Keeping this color as is, assuming it is used for foreground text
color_bg1 = '#3c3836'   # Keeping this color as is, assuming it is used for the background
color_bg3 = '#665c54'   # Keeping this color as is, assuming it is used for the background
color_blue = '#83aaff'  # Lighter shade of blue
color_aqua = '#89b8c2'  # Light blue-aqua
color_orange = '#d65d0e' # Keeping this color as is, assuming it is an accent color
color_purple = '#5f86b3' # Light blue with a slight hint of purple
color_mauve = '#89c3eb'  # Light blue with a hint of gray
color_red = '#cc241d'    # Keeping this color as is, assuming it is an accent color
color_yellow = '#d79921' # Keeping this color as is, assuming it is an accent color
color_gray = '#44475a'   # Keeping this color as is, assuming it is used for neutral elements

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg0"
style_root = "bg:color_bg1 fg:color_fg0"
format = '[ P! ]($style)'

[directory]
style = "fg:color_fg0 bg:color_purple"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_mauve"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_mauve)]($style)'

[git_status]
style = "bg:color_mauve"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_mauve)]($style)'

[nodejs]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_gray)]($style)'

[c]
symbol = " "
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_gray)]($style)'

[rust]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_gray)]($style)'

[golang]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_gray)]($style)'

[php]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_gray)]($style)'

[java]
symbol = " "
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_gray)]($style)'

[kotlin]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_gray)]($style)'

[haskell]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_gray)]($style)'

[python]
symbol = ""
style = "bg:color_gray"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_gray)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[\$](bold fg:green)'
error_symbol = '[x](bold fg:color_red)'
vimcmd_symbol = '[<](bold fg:green)'
vimcmd_replace_one_symbol = '[<](bold fg:color_purple)'
vimcmd_replace_symbol = '[<](bold fg:color_purple)'
vimcmd_visual_symbol = '[<](bold fg:color_yellow)'
