live_config_reload = true

import = [
    "~/.config/alacritty/themes/ashes_dark.toml",
]

[env]
TERM = "xterm-256color"

# Font settings
[font]
size = 10.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Window settings
[window.padding]
x = 5
y = 5

[window]
decorations = "None"
opacity = 0.97
option_as_alt = "Both"

[window.dimensions]
columns =  150
lines = 120
